### ISSUE TITLE
`NEWS100` is not a valid name with Flake8 >5

### ISSUE THREAD

**Issue by janmayer** [mobility-university/flake8-newspaper-style#3]
With flake8 >5, trying to use flake8-newspaper-style results in the error
```
plugin code for `flake8-newspaper-style[NEWS100]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

I guess NEWS100 has to be renamed to NWS100 or similar.

**Comment by cyyc1** [comment]
Hello @lindt , could you take a look at this issue here?

It should be a fairly simple code change. Thank you very much!

**Comment by lindt** [comment]
thanks for mentioning.
it should be resolved with version 0.4.0.
Worked just now with the current flake v5 version. Please try it out.
Will close it here, but let's reopen once it fails for you.
Thx.

**Comment by cyyc1** [comment]
Hi @lindt , thank you for making the change! The newest release is 0.3.0, but I noticed that you bumped the version to 0.4.0 in the code. Could you create a new release and publish it to PyPI? Thanks!

**Comment by lindt** [comment]
@cyyc1 : it was already in PyPI. Just forgot to tag it in github. Now it's also in github tagged. Thanks.
